---
title: "Data Cleaning and Transformation"
author: "Helitha Dharmadasa - z5451805"
date: "2024-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library("AER")
library("stringr")
```

## Read Data

```{r}
claims_data <- read_csv('../data/internal/UNSW_claims_data.csv', col_names = TRUE)

earned_data <- read_csv('../data/internal/UNSW_earned_data_adjusted_Sep27.csv', col_names = TRUE)

prediction_data <- read_csv('../data/internal/New_Customers_Pricing_Output_File.csv', col_names = TRUE)
```
# Prediction data cleaning

```{r}
prediction_data <- prediction_data %>% 
  mutate(train_flag = FALSE,
         earned_units = 1,
         nb_policy_first_inception_date = as.POSIXct("2024-11-01 17:00:00"),
         tenure = 0) %>%
  select(-Full_month_premium)

prediction_data <- prediction_data %>%
  filter(!(nb_breed_trait %in% c("siamese", "forest cat", "spotted cats", "persian", "burmese")))
```

# Claims Data Cleaning

```{r}
# Some cleaning
# Remove negative tenures (makes no sense)
# Remove 0 total claim amounts
# Treat $0 payments as no claim
claims_data <- claims_data %>%
  filter(tenure >= 0) %>% 
  filter(total_claim_amount > 0)

claims_data <- claims_data %>%
  filter(!str_detect(claim_status, "not_paid"))

# Get rid of duplicates across all columns - probably errors
claims_data <- claims_data %>%
  distinct()

# Group remaining duplicate claim_ids
claims_data <- claims_data %>%
  group_by(claim_start_date, claim_id, tenure, exposure_id) %>%
  summarise(claim_status = paste(unique(claim_status), collapse = ", "),
            condition_category = paste(unique(condition_category), collapse = ", "),  
            claim_paid = sum(claim_paid),
            total_claim_amount = sum(total_claim_amount))

earned_data <- earned_data %>% 
  mutate(train_flag = TRUE) 
```

# Earned Data Cleaning

```{r}
# Cleaning steps only to apply to training data

# Remove negative tenures
earned_data <- earned_data %>%
  filter(tenure >= 0)

# earned_units in months with claims is set to 0 for some reason, correct this to 1.
# Earned units with incredibly small values are nonsensical - set to 1 for tenures >= 0
# Or calculate for tenures == 0
earned_data <- earned_data %>%
  mutate(days_in_month = days_in_month(nb_policy_first_inception_date),
    earned_units_manual = pmax(days_in_month - day(nb_policy_first_inception_date), 1) / days_in_month,
    earned_units = case_when(
      tenure == 0 & earned_units <= 1e-10 ~ earned_units_manual,
      tenure != 0 & earned_units <= 1e-10 ~ 1,
      TRUE ~ earned_units
    )
 ) %>% select(-earned_units_manual, -days_in_month)

earned_data <- earned_data %>% 
  select(-c("...1", "UW_Date", "row_num", "exposure_id_1"))
```


```{r}
# Bind prediction and earned data for next transformations
earned_data <- bind_rows(earned_data, prediction_data)
```


```{r}
# Clean up pet_de_sexed_age factorsx
earned_data <- earned_data %>%
  mutate(pet_de_sexed_age = case_when(
    str_detect(pet_de_sexed_age, "0-3") ~ "0-3 months",
    str_detect(pet_de_sexed_age, "4-6") ~ "4-6 months",
    str_detect(pet_de_sexed_age, "7-12") ~ "7-12 months",
    str_detect(pet_de_sexed_age, "1-2") ~ "1-2 years",
    str_detect(pet_de_sexed_age, "2\\+") ~ "2+ years"
  )) %>%
  replace_na(list(pet_de_sexed_age = "FALSE"))

# Replace missing breed traits with unknown
earned_data <- earned_data %>%
  replace_na(list(nb_breed_trait = "unknown"))

# Replace missing switcher status with FALSE
earned_data <- earned_data %>%
  replace_na(list(pet_is_switcher = FALSE))

# Compute median ages by postcode
age_df <- earned_data %>%
  group_by(nb_postcode) %>%
  summarise(median_age = floor(median(owner_age_years, na.rm = TRUE)))

# Impute age and DoB using median, DoB is clunky but we won't use anyway
earned_data <- earned_data %>%
  left_join(age_df, by="nb_postcode") %>%
  mutate(owner_age_years = coalesce(owner_age_years, median_age)) %>%
  mutate(person_dob = coalesce(person_dob, as.Date(paste0(2024 - owner_age_years, "-01-01")))) %>%
  select(-median_age)

```


# Join Density data
```{r}
density_data <- read_csv('../data/external/MMM areas classification.csv') %>%
  rename(mm_category = MMM)

earned_data <- left_join(earned_data, density_data, by = c("nb_suburb", "nb_postcode", "nb_state"))
```



# Join Income Data
```{r}
income_data <-read_csv('../data/external/Median Income.csv') %>% rename(median_income = `Median total income($)`)


# Perform a left join (UNSW earned data left join with external data based on postcode)
earned_data <- income_data %>% select("nb_postcode", "nb_suburb", "nb_state", "median_income") %>%
  right_join(earned_data, by = c("nb_suburb", "nb_postcode", "nb_state"))

income_df <- income_data %>%
  group_by(nb_state) %>%
  summarise(imputed_median_income = median(median_income, na.rm = TRUE))

earned_data <- earned_data %>%
  left_join(income_df, by="nb_state") %>%
    mutate(median_income = coalesce(median_income, imputed_median_income)) %>%
  select(-imputed_median_income)
```

```{r}
prediction_df <- earned_data %>%
  filter(train_flag == FALSE) %>%
  mutate(mm_category = coalesce(mm_category, 1)) %>%
  select(-train_flag)

earned_data <- earned_data %>%
  filter(train_flag == TRUE) %>%
  select(-train_flag)
```

# Frequency Data

```{r}
# Calculate claims count (treat $0 claims as non-existent)
claims_count <- claims_data %>% 
  filter(claim_paid > 0) %>%
  group_by(exposure_id, tenure) %>% 
  summarise(claim_count = n(), .groups = 'drop')

frequency_df <- left_join(earned_data, claims_count, by = c("exposure_id", "tenure"))

frequency_df <- frequency_df %>%
  mutate(claim_count = replace_na(claim_count, 0),
         claim_count_indicator = ifelse(claim_count > 0, 1, 0))
```

# Severity Data

```{r}
# Calculate claims severity (treat $0 claims as non-existent)
severity_df <- claims_data %>%
  filter(claim_paid > 0) %>%
  left_join(earned_data, by = c("exposure_id", "tenure"))
```


# Joint (Tweedie) Data

```{r}
joint_df <- claims_data %>% 
  group_by(exposure_id, tenure) %>%
  summarise(claim_paid = sum(claim_paid),
            total_claim_amount = sum(total_claim_amount)) %>% 
  full_join(earned_data, by = c("exposure_id", "tenure")) %>%
  mutate(total_claim_amount = replace_na(total_claim_amount, 0),
         claim_paid = replace_na(claim_paid, 0))
```

```{r}

write_csv(frequency_df, "../data/transformed/frequency.csv")

write_csv(severity_df, "../data/transformed/severity.csv")

write_csv(joint_df, "../data/transformed/joint.csv")

write_csv(prediction_df, "../data/transformed/prediction.csv")
```

```{r}
summary(frequency_df)
summary(severity_df)
summary(joint_df)
```



