---
title: "Modelling"
author: "Helitha Dharmadasa - z5451805"
date: "2024-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```


```{r}
# Read data
frequency_predictions <- read_csv('../data/transformed/frequency_predictions.csv', col_names = TRUE)

severity_predictions <- read_csv('../data/transformed/severity_predictions.csv', col_names = TRUE)

prediction_data <- read_csv('../data/internal/New_Customers_Pricing_Output_File.csv', col_names = TRUE)
```

```{r}
# Assign loss ratio
loss_ratio = 0.8

# Calculate full month premiums
prediction_df <- frequency_predictions %>%
  mutate(predicted_claim_paid = severity_predictions$predicted_claim_paid,
         predicted_claim_cost = predicted_claim_count * predicted_claim_paid,
         Full_month_premium = predicted_claim_cost / loss_ratio)

```

```{r}
# Attach premiums back to original submission file without cats
prediction_data <- prediction_data %>%
  filter(!(nb_breed_trait %in% c("siamese", "forest cat", "spotted cats", "persian", "burmese")))

prediction_data <- prediction_data %>%
  mutate(Full_month_premium = round(prediction_df$Full_month_premium,2))
```

```{r}
# Write file
write_csv(prediction_data, '../data/SUBMISSION_New_Customers_Pricing_Output_File.csv')
```













